- hosts: node1
  remote_user: root

  tasks:
    - name: add gluster peer nodes
      shell: for i in {1..3};do gluster peer probe node$i;done

    - name: create replica volume
      shell: gluster vol create vol1 replica 3 node{1..3}:/gluster/brick1;gluster vol start vol1;gluster vol info
    - name: create ec volume
      shell: gluster vol create vol1 disperse-data 2 redundancy 1 node{1..3}:/gluster/brick1;gluster vol start vol1;gluster vol info
